"""
Python bindings for FIDESlib (CKKS on GPU, interoperable with OpenFHE)
"""
from __future__ import annotations
import numpy
import typing
__all__: list[str] = ['ADVANCEDSHE', 'CCParams', 'Ciphertext', 'CryptoContext', 'FHE', 'FIXEDAUTO', 'FIXEDMANUAL', 'FLEXIBLEAUTO', 'FLEXIBLEAUTOEXT', 'GAUSSIAN', 'GenCryptoContext', 'GetChebyshevCoefficients', 'HEStd_128_classic', 'HEStd_128_quantum', 'HEStd_192_classic', 'HEStd_192_quantum', 'HEStd_256_classic', 'HEStd_256_quantum', 'HEStd_NotSet', 'HYBRID', 'KEYSWITCH', 'KeyPair', 'KeySwitchTechnique', 'LEVELEDSHE', 'MULTIPARTY', 'PKE', 'PKESchemeFeature', 'PRE', 'Plaintext', 'PrivateKey', 'PublicKey', 'SCHEMESWITCH', 'SPARSE_ENCAPSULATED', 'SPARSE_TERNARY', 'ScalingTechnique', 'SecretKeyDist', 'SecurityLevel', 'UNIFORM_TERNARY', 'accumulate_rotation_indices']
class CCParams:
    def GetBatchSize(self) -> int:
        ...
    def GetMultiplicativeDepth(self) -> int:
        ...
    def SetBatchSize(self, arg0: int) -> None:
        ...
    def SetCiphertextAutoload(self, arg0: bool) -> None:
        ...
    def SetDevices(self, devices: list[int]) -> None:
        ...
    def SetDigitSize(self, arg0: int) -> None:
        ...
    def SetFirstModSize(self, arg0: int) -> None:
        ...
    def SetKeySwitchTechnique(self, arg0: KeySwitchTechnique) -> None:
        ...
    def SetMultiplicativeDepth(self, arg0: int) -> None:
        ...
    def SetNumLargeDigits(self, arg0: int) -> None:
        ...
    def SetPlaintextAutoload(self, arg0: bool) -> None:
        ...
    def SetRingDim(self, arg0: int) -> None:
        ...
    def SetScalingModSize(self, arg0: int) -> None:
        ...
    def SetScalingTechnique(self, arg0: ScalingTechnique) -> None:
        ...
    def SetSecretKeyDist(self, arg0: SecretKeyDist) -> None:
        ...
    def SetSecurityLevel(self, arg0: SecurityLevel) -> None:
        ...
    def __init__(self) -> None:
        ...
class Ciphertext:
    def Clone(self) -> Ciphertext:
        ...
    def GetLevel(self) -> int:
        ...
    def GetNoiseScaleDeg(self) -> int:
        ...
    def IsOffloaded(self) -> bool:
        ...
    def Offload(self) -> None:
        ...
    def Reload(self) -> None:
        ...
    def SetSlots(self, slots: int) -> None:
        ...
class CryptoContext:
    def AccumulateSum(self, ciphertext: Ciphertext, slots: int, stride: int = 1) -> Ciphertext:
        ...
    def AccumulateSumInPlace(self, ciphertext: Ciphertext, slots: int, stride: int = 1) -> None:
        ...
    def Decrypt(self, privateKey: PrivateKey, ciphertext: Ciphertext) -> Plaintext:
        ...
    def Enable(self, feature: PKESchemeFeature) -> None:
        ...
    def Encrypt(self, publicKey: PublicKey, plaintext: Plaintext) -> Ciphertext:
        ...
    @typing.overload
    def EvalAdd(self, arg0: Ciphertext, arg1: Ciphertext) -> Ciphertext:
        ...
    @typing.overload
    def EvalAdd(self, arg0: Ciphertext, arg1: Plaintext) -> Ciphertext:
        ...
    @typing.overload
    def EvalAdd(self, arg0: Ciphertext, arg1: float) -> Ciphertext:
        ...
    @typing.overload
    def EvalAdd(self, arg0: float, arg1: Ciphertext) -> Ciphertext:
        ...
    @typing.overload
    def EvalAddInPlace(self, arg0: Ciphertext, arg1: Ciphertext) -> None:
        ...
    @typing.overload
    def EvalAddInPlace(self, arg0: Ciphertext, arg1: Plaintext) -> None:
        ...
    @typing.overload
    def EvalAddInPlace(self, arg0: Ciphertext, arg1: float) -> None:
        ...
    def EvalBootstrap(self, ciphertext: Ciphertext, numIterations: int = 1, precision: int = 0, prescaled: bool = False) -> Ciphertext:
        ...
    def EvalBootstrapKeyGen(self, privateKey: PrivateKey, slots: int) -> None:
        ...
    def EvalBootstrapSetup(self, levelBudget: list[int] = [5, 4], dim1: list[int] = [0, 0], slots: int = 0, correctionFactor: int = 0, precompute: bool = True, btsfirstboot: bool = False) -> None:
        ...
    def EvalChebyshevSeries(self, ciphertext: Ciphertext, coefficients: list[float], a: float, b: float) -> Ciphertext:
        ...
    def EvalChebyshevSeriesInPlace(self, ciphertext: Ciphertext, coefficients: list[float], a: float, b: float) -> None:
        ...
    @typing.overload
    def EvalMult(self, arg0: Ciphertext, arg1: Ciphertext) -> Ciphertext:
        ...
    @typing.overload
    def EvalMult(self, arg0: Ciphertext, arg1: Plaintext) -> Ciphertext:
        ...
    @typing.overload
    def EvalMult(self, arg0: Ciphertext, arg1: float) -> Ciphertext:
        ...
    @typing.overload
    def EvalMult(self, arg0: float, arg1: Ciphertext) -> Ciphertext:
        ...
    @typing.overload
    def EvalMultInPlace(self, arg0: Ciphertext, arg1: Plaintext) -> None:
        ...
    @typing.overload
    def EvalMultInPlace(self, arg0: Ciphertext, arg1: float) -> None:
        ...
    def EvalMultKeyGen(self, privateKey: PrivateKey) -> None:
        ...
    def EvalNegate(self, arg0: Ciphertext) -> Ciphertext:
        ...
    def EvalRotate(self, ciphertext: Ciphertext, index: int) -> Ciphertext:
        ...
    def EvalRotateInPlace(self, ciphertext: Ciphertext, index: int) -> None:
        ...
    def EvalRotateKeyGen(self, privateKey: PrivateKey, indexList: list[int]) -> None:
        ...
    def EvalSquare(self, arg0: Ciphertext) -> Ciphertext:
        ...
    @typing.overload
    def EvalSub(self, arg0: Ciphertext, arg1: Ciphertext) -> Ciphertext:
        ...
    @typing.overload
    def EvalSub(self, arg0: Ciphertext, arg1: Plaintext) -> Ciphertext:
        ...
    @typing.overload
    def EvalSub(self, arg0: Ciphertext, arg1: float) -> Ciphertext:
        ...
    @typing.overload
    def EvalSub(self, arg0: float, arg1: Ciphertext) -> Ciphertext:
        ...
    @typing.overload
    def EvalSubInPlace(self, arg0: Ciphertext, arg1: Ciphertext) -> None:
        ...
    @typing.overload
    def EvalSubInPlace(self, arg0: Ciphertext, arg1: float) -> None:
        ...
    def GetCyclotomicOrder(self) -> int:
        ...
    def GetRingDimension(self) -> int:
        ...
    def KeyGen(self) -> KeyPair:
        ...
    def LoadCiphertext(self, ciphertext: Ciphertext) -> None:
        ...
    def LoadContext(self, publicKey: PublicKey) -> None:
        ...
    def LoadPlaintext(self, plaintext: Plaintext) -> None:
        ...
    def MakeCKKSPackedPlaintext(self, value: list[float], noiseScaleDeg: int = 1, level: int = 0, slots: int = 0) -> Plaintext:
        ...
    def MakeCKKSPackedPlaintextF64(self, value: numpy.ndarray[typing.Any, numpy.dtype[numpy.float64]], noiseScaleDeg: int = 1, level: int = 0, slots: int = 0) -> Plaintext:
        ...
    def Rescale(self, arg0: Ciphertext) -> Ciphertext:
        ...
    def RescaleInPlace(self, arg0: Ciphertext) -> None:
        ...
    def SetAutoLoadCiphertexts(self, arg0: bool) -> None:
        ...
    def SetAutoLoadPlaintexts(self, arg0: bool) -> None:
        ...
    def SetDevices(self, devices: list[int]) -> None:
        ...
    def Synchronize(self) -> None:
        ...
    def TrimGPUMemoryPool(self) -> None:
        ...
class KeyPair:
    @property
    def publicKey(self) -> PublicKey:
        ...
    @property
    def secretKey(self) -> PrivateKey:
        ...
class KeySwitchTechnique:
    """
    Members:
    
      HYBRID
    """
    HYBRID: typing.ClassVar[KeySwitchTechnique]  # value = <KeySwitchTechnique.HYBRID: 2>
    __members__: typing.ClassVar[dict[str, KeySwitchTechnique]]  # value = {'HYBRID': <KeySwitchTechnique.HYBRID: 2>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class PKESchemeFeature:
    """
    Members:
    
      PKE
    
      KEYSWITCH
    
      PRE
    
      LEVELEDSHE
    
      ADVANCEDSHE
    
      MULTIPARTY
    
      FHE
    
      SCHEMESWITCH
    """
    ADVANCEDSHE: typing.ClassVar[PKESchemeFeature]  # value = <PKESchemeFeature.ADVANCEDSHE: 16>
    FHE: typing.ClassVar[PKESchemeFeature]  # value = <PKESchemeFeature.FHE: 64>
    KEYSWITCH: typing.ClassVar[PKESchemeFeature]  # value = <PKESchemeFeature.KEYSWITCH: 2>
    LEVELEDSHE: typing.ClassVar[PKESchemeFeature]  # value = <PKESchemeFeature.LEVELEDSHE: 8>
    MULTIPARTY: typing.ClassVar[PKESchemeFeature]  # value = <PKESchemeFeature.MULTIPARTY: 32>
    PKE: typing.ClassVar[PKESchemeFeature]  # value = <PKESchemeFeature.PKE: 1>
    PRE: typing.ClassVar[PKESchemeFeature]  # value = <PKESchemeFeature.PRE: 4>
    SCHEMESWITCH: typing.ClassVar[PKESchemeFeature]  # value = <PKESchemeFeature.SCHEMESWITCH: 128>
    __members__: typing.ClassVar[dict[str, PKESchemeFeature]]  # value = {'PKE': <PKESchemeFeature.PKE: 1>, 'KEYSWITCH': <PKESchemeFeature.KEYSWITCH: 2>, 'PRE': <PKESchemeFeature.PRE: 4>, 'LEVELEDSHE': <PKESchemeFeature.LEVELEDSHE: 8>, 'ADVANCEDSHE': <PKESchemeFeature.ADVANCEDSHE: 16>, 'MULTIPARTY': <PKESchemeFeature.MULTIPARTY: 32>, 'FHE': <PKESchemeFeature.FHE: 64>, 'SCHEMESWITCH': <PKESchemeFeature.SCHEMESWITCH: 128>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class Plaintext:
    def GetCKKSPackedValue(self) -> list[complex]:
        ...
    def GetLevel(self) -> int:
        ...
    def GetLogPrecision(self) -> float:
        ...
    def GetRealPackedValue(self) -> list[float]:
        ...
    def SetLength(self, length: int) -> None:
        ...
    def SetSlots(self, slots: int) -> None:
        ...
    def UnloadFromDevice(self) -> None:
        ...
    def __str__(self) -> str:
        ...
class PrivateKey:
    pass
class PublicKey:
    pass
class ScalingTechnique:
    """
    Members:
    
      FIXEDMANUAL
    
      FIXEDAUTO
    
      FLEXIBLEAUTO
    
      FLEXIBLEAUTOEXT
    """
    FIXEDAUTO: typing.ClassVar[ScalingTechnique]  # value = <ScalingTechnique.FIXEDAUTO: 1>
    FIXEDMANUAL: typing.ClassVar[ScalingTechnique]  # value = <ScalingTechnique.FIXEDMANUAL: 0>
    FLEXIBLEAUTO: typing.ClassVar[ScalingTechnique]  # value = <ScalingTechnique.FLEXIBLEAUTO: 2>
    FLEXIBLEAUTOEXT: typing.ClassVar[ScalingTechnique]  # value = <ScalingTechnique.FLEXIBLEAUTOEXT: 3>
    __members__: typing.ClassVar[dict[str, ScalingTechnique]]  # value = {'FIXEDMANUAL': <ScalingTechnique.FIXEDMANUAL: 0>, 'FIXEDAUTO': <ScalingTechnique.FIXEDAUTO: 1>, 'FLEXIBLEAUTO': <ScalingTechnique.FLEXIBLEAUTO: 2>, 'FLEXIBLEAUTOEXT': <ScalingTechnique.FLEXIBLEAUTOEXT: 3>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class SecretKeyDist:
    """
    Members:
    
      GAUSSIAN
    
      UNIFORM_TERNARY
    
      SPARSE_TERNARY
    
      SPARSE_ENCAPSULATED
    """
    GAUSSIAN: typing.ClassVar[SecretKeyDist]  # value = <SecretKeyDist.GAUSSIAN: 0>
    SPARSE_ENCAPSULATED: typing.ClassVar[SecretKeyDist]  # value = <SecretKeyDist.SPARSE_ENCAPSULATED: 3>
    SPARSE_TERNARY: typing.ClassVar[SecretKeyDist]  # value = <SecretKeyDist.SPARSE_TERNARY: 2>
    UNIFORM_TERNARY: typing.ClassVar[SecretKeyDist]  # value = <SecretKeyDist.UNIFORM_TERNARY: 1>
    __members__: typing.ClassVar[dict[str, SecretKeyDist]]  # value = {'GAUSSIAN': <SecretKeyDist.GAUSSIAN: 0>, 'UNIFORM_TERNARY': <SecretKeyDist.UNIFORM_TERNARY: 1>, 'SPARSE_TERNARY': <SecretKeyDist.SPARSE_TERNARY: 2>, 'SPARSE_ENCAPSULATED': <SecretKeyDist.SPARSE_ENCAPSULATED: 3>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class SecurityLevel:
    """
    Members:
    
      HEStd_128_classic
    
      HEStd_192_classic
    
      HEStd_256_classic
    
      HEStd_128_quantum
    
      HEStd_192_quantum
    
      HEStd_256_quantum
    
      HEStd_NotSet
    """
    HEStd_128_classic: typing.ClassVar[SecurityLevel]  # value = <SecurityLevel.HEStd_128_classic: 0>
    HEStd_128_quantum: typing.ClassVar[SecurityLevel]  # value = <SecurityLevel.HEStd_128_quantum: 3>
    HEStd_192_classic: typing.ClassVar[SecurityLevel]  # value = <SecurityLevel.HEStd_192_classic: 1>
    HEStd_192_quantum: typing.ClassVar[SecurityLevel]  # value = <SecurityLevel.HEStd_192_quantum: 4>
    HEStd_256_classic: typing.ClassVar[SecurityLevel]  # value = <SecurityLevel.HEStd_256_classic: 2>
    HEStd_256_quantum: typing.ClassVar[SecurityLevel]  # value = <SecurityLevel.HEStd_256_quantum: 5>
    HEStd_NotSet: typing.ClassVar[SecurityLevel]  # value = <SecurityLevel.HEStd_NotSet: 6>
    __members__: typing.ClassVar[dict[str, SecurityLevel]]  # value = {'HEStd_128_classic': <SecurityLevel.HEStd_128_classic: 0>, 'HEStd_192_classic': <SecurityLevel.HEStd_192_classic: 1>, 'HEStd_256_classic': <SecurityLevel.HEStd_256_classic: 2>, 'HEStd_128_quantum': <SecurityLevel.HEStd_128_quantum: 3>, 'HEStd_192_quantum': <SecurityLevel.HEStd_192_quantum: 4>, 'HEStd_256_quantum': <SecurityLevel.HEStd_256_quantum: 5>, 'HEStd_NotSet': <SecurityLevel.HEStd_NotSet: 6>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
def GenCryptoContext(params: CCParams) -> CryptoContext:
    ...
def GetChebyshevCoefficients(func: typing.Callable, a: float, b: float, degree: int) -> list[float]:
    """
    Chebyshev interpolation coefficients of a Python callable on [a, b].
    """
def accumulate_rotation_indices(slots: int, stride: int = 1, bstep: int = 4) -> list[int]:
    """
    Rotation indices required by AccumulateSum(ct, slots, stride). Pass them to EvalRotateKeyGen.
    """
ADVANCEDSHE: PKESchemeFeature  # value = <PKESchemeFeature.ADVANCEDSHE: 16>
FHE: PKESchemeFeature  # value = <PKESchemeFeature.FHE: 64>
FIXEDAUTO: ScalingTechnique  # value = <ScalingTechnique.FIXEDAUTO: 1>
FIXEDMANUAL: ScalingTechnique  # value = <ScalingTechnique.FIXEDMANUAL: 0>
FLEXIBLEAUTO: ScalingTechnique  # value = <ScalingTechnique.FLEXIBLEAUTO: 2>
FLEXIBLEAUTOEXT: ScalingTechnique  # value = <ScalingTechnique.FLEXIBLEAUTOEXT: 3>
GAUSSIAN: SecretKeyDist  # value = <SecretKeyDist.GAUSSIAN: 0>
HEStd_128_classic: SecurityLevel  # value = <SecurityLevel.HEStd_128_classic: 0>
HEStd_128_quantum: SecurityLevel  # value = <SecurityLevel.HEStd_128_quantum: 3>
HEStd_192_classic: SecurityLevel  # value = <SecurityLevel.HEStd_192_classic: 1>
HEStd_192_quantum: SecurityLevel  # value = <SecurityLevel.HEStd_192_quantum: 4>
HEStd_256_classic: SecurityLevel  # value = <SecurityLevel.HEStd_256_classic: 2>
HEStd_256_quantum: SecurityLevel  # value = <SecurityLevel.HEStd_256_quantum: 5>
HEStd_NotSet: SecurityLevel  # value = <SecurityLevel.HEStd_NotSet: 6>
HYBRID: KeySwitchTechnique  # value = <KeySwitchTechnique.HYBRID: 2>
KEYSWITCH: PKESchemeFeature  # value = <PKESchemeFeature.KEYSWITCH: 2>
LEVELEDSHE: PKESchemeFeature  # value = <PKESchemeFeature.LEVELEDSHE: 8>
MULTIPARTY: PKESchemeFeature  # value = <PKESchemeFeature.MULTIPARTY: 32>
PKE: PKESchemeFeature  # value = <PKESchemeFeature.PKE: 1>
PRE: PKESchemeFeature  # value = <PKESchemeFeature.PRE: 4>
SCHEMESWITCH: PKESchemeFeature  # value = <PKESchemeFeature.SCHEMESWITCH: 128>
SPARSE_ENCAPSULATED: SecretKeyDist  # value = <SecretKeyDist.SPARSE_ENCAPSULATED: 3>
SPARSE_TERNARY: SecretKeyDist  # value = <SecretKeyDist.SPARSE_TERNARY: 2>
UNIFORM_TERNARY: SecretKeyDist  # value = <SecretKeyDist.UNIFORM_TERNARY: 1>
